services:
  mongodb:
    image: mongo:latest
    container_name: mongo-memelandia
    restart: always 
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: memelandia
  postgresdb:
    image: postgres:15-alpine
    container_name: postgres-memelandia
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:latest
    container_name: memelandia-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  meme-rabbitmq:
    image: rabbitmq:3-management
    container_name: meme-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - memelandia-network
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-memelandia
    restart: always
    ports:
      - "9411:9411"
    networks:
      - memelandia-network
networks:
  memelandia-network:
    driver: bridge
