spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: google
              uri: https://google.com
              predicates:
                - Path=/search**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted