spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      observability:
        enabled: true
      server:
        webflux:
          routes:
            - id: google
              uri: https://google.com
              predicates:
                - Path=/search**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000