server:
  port: 8888
endpoints:
  restart:
    enabled: true
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
